else if strncmp('mul', line, 3){ return 2; }
    // else if strncmp('and', line, 3){ return 3; }
    // else if strncmp('or', line, 3){ return 4; }
    // else if strncmp('xor', line, 3){ return 5; }
    // else if strncmp('sll', line, 3){ return 6; }
    // else if strncmp('sra', line, 3){ return 7; }
    // else if strncmp('srl', line, 3){ return 8; }
    // else if strncmp('beq', line, 3){ return 9; }
    // else if strncmp('bne', line, 3){ return 10; }
    // else if strncmp('blt', line, 3){ return 11; }
    // else if strncmp('bgt', line, 3){ return 12; }
    // else if strncmp('ble', line, 3){ return 13; }
    // else if strncmp('bge', line, 3){ return 14; }
    // else if strncmp('jal', line, 3){ return 15; }
    // else if strncmp('lw', line, 2){ return 16; }
    // else if strncmp('sw', line, 2){ return 17; }
    // else if strncmp('reti', line, 4){ return 18; }
    // else if strncmp('in', line, 2){ return 19; }
    // else if strncmp('out', line, 3){ return 20; }
    // else if strncmp('halt', line, 4){ return 21; }